#!bin/bash -x
Rollingdie=$(( RANDOM % 6))
echo $Rollingdie
if [ $Rollingdie -le 6 ]
then
echo "play the game"
else 
echo "stop the game"
declare -A Rollingdie
Rollingdie[1]="move the token forward into first position"
Rollingdie[2]="move the token forward into second position"
Rollingdie[3]="move the token forward into third position"
Rollingdie[4]="move the token forward into fourth position"
Rollingdie[5]="move the token forward into fifth position"
Rollingdie[6]="move the token forward into sixth position"
echo "enter the integer"
read integer
for((i=0;i<10;i++))
do 
  echo $i
done
esac
